package ru.ayeaye.game.model;

public enum Attribute {
	DESCRIPTION_STRING,
	HIT_POINTS_INT,
	ATTACK_POINTS_INT,
	INVENTORY_GAME_OBJECT_LIST,
	MELE_ATTACK_SPEED_FLOAT,
	MOVE_SPEED_FLOAT,
	CONJURE_SPEED_FLOAT
}
